<a href="https://colab.research.google.com/github/pavani93901/Numpy_assignment-2/blob/main/Numpy_assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
cricket_df = pd.read_csv("/content/Indian_Cricket_Team_Dataset.csv")
cricket_df

Player Name  Age  Matches Played  Batting Average  Strike Rate
0       Player_1   26             456            27.70       188.21
1       Player_2   23             154            24.61       139.34
2       Player_3   32             210            36.87       182.79
3       Player_4   34             426            51.81       178.77
4       Player_5   30             221            49.80       162.44
..           ...  ...             ...              ...          ...
995   Player_996   24             279            23.46       187.80
996   Player_997   28             344            29.47       160.55
997   Player_998   23             126            49.30       124.71
998   Player_999   35              16            41.93       135.59
999  Player_1000   30             146            25.12       108.39

[1000 rows x 5 columns]

#Query 1: Convert 'Age' column to a NumPy array.

In [4]:
ages_array = np.array(cricket_df['Age'])
print(type(ages_array))

<class 'numpy.ndarray'>


# Query 2: Find the average age of players.

In [5]:
average_age = np.mean(ages_array)
print(average_age)

27.57


#Query 3: Find the oldest and youngest player age.

In [6]:
oldest_age = np.max(ages_array)
youngest_age = np.min(ages_array)

print(oldest_age)
print(youngest_age)

35
20


#Query 4: Count the total number of players above 30 years old.

In [7]:
count_above_30 = np.sum(ages_array > 30)
print(count_above_30)


336


# Query 5: Find the median batting average.

In [8]:
batting_avg_array = np.array(cricket_df['Batting Average'])
median_batting_avg = np.median(batting_avg_array)

print(median_batting_avg)

40.135


# Query 6: Find the standard deviation of strike rates.

In [9]:
strike_rate_array = np.array(cricket_df['Strike Rate'])
std_dev_strike_rate = np.std(strike_rate_array)

print(std_dev_strike_rate)

29.10819410384471


# Query 7: Find the 90th percentile of batting average.

In [10]:

percentile_90 = np.percentile(batting_avg_array, 90)

print(percentile_90)

55.323


# Query 8: Find the number of players with strike rate above 150.

In [14]:
strike_rate_array = np.array(cricket_df['Strike Rate'])
high_strike_rate = strike_rate_array > 150
count_high_strike = np.sum(high_strike_rate)
print(count_high_strike)

513


# Query 9: Reshape the first 20 batting averages into a 4x5 matrix.

In [15]:
reshaped_avg = batting_avg_array[:20].reshape(4,5)
print(reshaped_avg)

[[27.7  24.61 36.87 51.81 49.8 ]
 [22.2  38.21 40.9  45.78 46.01]
 [34.59 42.43 39.24 55.4  41.21]
 [37.64 36.18 42.9  52.16 41.54]]


# Query 10: Compute row-wise sum of reshaped matrix.

In [16]:

row_wise_sum = np.sum(reshaped_avg, axis=1)
print(row_wise_sum)

[190.79 193.1  212.87 210.42]


# Query 11: Compute column-wise mean of reshaped matrix.

In [17]:
col_wise_mean = np.mean(reshaped_avg, axis=0)
print(col_wise_mean)

[30.5325 35.3575 39.9775 51.2875 44.64  ]


# Query 12: Transpose the reshaped matrix.

In [ ]:
transposed_avg = reshaped_avg.T
print(transposed_avg)


# Query 13: Find the variance of batting average.

In [18]:
variance_batting_avg = np.var(batting_avg_array)

print(variance_batting_avg)

131.5398293159


# Query 14: Stack age and matches played horizontally.

In [20]:
matches_array = np.array(cricket_df['Matches Played']) # Define matches_array here by extracting it from the DataFrame
stacked_array = np.hstack((ages_array.reshape(-1,1), matches_array.reshape(-1,1)))

print(stacked_array)

[[ 26 456]
 [ 23 154]
 [ 32 210]
 ...
 [ 23 126]
 [ 35  16]
 [ 30 146]]


# Query 15: Split the batting average array into 100 equal parts.

In [21]:
split_avg = np.array_split(batting_avg_array, 100)
print(split_avg)

[array([27.7 , 24.61, 36.87, 51.81, 49.8 , 22.2 , 38.21, 40.9 , 45.78,
       46.01]), array([34.59, 42.43, 39.24, 55.4 , 41.21, 37.64, 36.18, 42.9 , 52.16,
       41.54]), array([46.47, 49.51, 40.81, 37.07, 55.07, 36.7 , 38.48, 59.61, 20.01,
       27.42]), array([35.36, 57.3 , 22.8 , 20.38, 22.11, 23.54, 21.5 , 39.19, 43.23,
       30.87]), array([35.93, 23.67, 33.45, 40.9 , 49.29, 20.13, 38.69, 31.88, 54.11,
       48.62]), array([43.56, 31.09, 56.41, 21.8 , 24.38, 35.67, 24.98, 58.26, 51.92,
       30.36]), array([43.54, 59.29, 55.37, 44.03, 56.15, 59.57, 49.73, 22.6 , 36.06,
       53.51]), array([29.22, 53.23, 24.81, 21.88, 35.36, 21.47, 58.29, 53.05, 52.03,
       45.19]), array([28.65, 40.73, 43.89, 41.  , 30.41, 40.61, 39.65, 59.85, 55.9 ,
       38.54]), array([44.92, 49.91, 21.39, 55.8 , 54.41, 38.3 , 35.65, 30.92, 39.07,
       21.78]), array([54.09, 21.42, 33.16, 57.26, 49.41, 31.26, 30.11, 20.2 , 47.83,
       21.95]), array([41.3 , 58.48, 24.38, 55.78, 59.66, 22.46, 55.3